# Generated by Django 4.2.3 on 2023-07-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('no_visualizaciones', models.IntegerField(default=0)),
                ('puntaje', models.FloatField(default=0)),
            ],
        ),
    ]
