# Generated by Django 4.2.3 on 2023-07-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_viewed_users_moviescore_movie_users_scored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviescore',
            old_name='movie',
            new_name='name',
        ),
    ]
