# Generated by Django 4.2.3 on 2023-07-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genero_movie_genre_rename_nombre_movie_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='visualizations',
            new_name='views',
        ),
    ]
