# Generated by Django 4.2.3 on 2023-07-27 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed_users',
            field=models.ManyToManyField(related_name='viewed_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='users_scored',
            field=models.ManyToManyField(related_name='scored_movies', through='movies.MovieScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
